### ISSUE TITLE
Can we have an analyzer for 'is' operator against UnityEngine.Object?

### ISSUE THREAD

**Issue by aybe** [microsoft/Microsoft.Unity.Analyzers#176]
#### Problem statement

Take the following code, it will not consider asset as `null` when it's `"null"` in the debugger:

```
ScriptableObject asset = ...;

if (asset is null)
{
    return;
}

// do something
```

#### Proposed solution

An analyzer that detects usage of `is` operator against `UnityEngine.Object` and warns that it won't work against `"null"` values.

The failproof solution is to use `==` instead:

```
ScriptableObject asset = ...;

if (asset == null)
{
    return;
}

// do something
```

**Comment by SilentSin** [comment]
We have an analyser against `?.` because there is no similar operator that respects destroyed objects.

That's not the case for `is`. If you want to also check for destroyed objects you can use `==` which uses the exact same number of characters. The only reason to use `is` is if you explicitly don't want it to do that, so it seems silly to warn against it.

**Comment by aybe** [comment]
You've made a point, actually, I should have been more precise.

The analyzer would detect if a comparaison again `UnityEngine.Object` is done with `is null` rather than simply checking the use of `is` operator against that type of object.

**Comment by SilentSin** [comment]
When I use `is null` that means I don't want it to check for destroyed objects so I don't want a warning telling me it's not going to check for destroyed objects. If I did want to check for destroyed objects, I would be using `== null`.

There are two operators you can choose between. Both take the same number of characters to write. It doesn't make sense to warn against using `is` just because it works differently from `==`. The choice to use `is` indicates that you want it to work like that.

**Comment by sailro** [comment]
cc @jbevain, what do you think?

**Comment by jbevain** [comment]
I tend to agree with @SilentSin here.

`x is null` is basically `Object.ReferenceEquals(x, null)` which is going to bypass a `==` operator.

Now you could make the case that a beginner could write `x is null` while meaning `== null` and that it could be beneficial to suggest them to double check if this is what they really want, but I don't know if an analyzer is the best user experience for this.

**Comment by sailro** [comment]
I agree, let's close this for now.

Thank you all for valuable feedback!
