### ISSUE TITLE
IDE0051 using runtime data

### ISSUE THREAD

**Issue by yonggyun-superlazy** [microsoft/Microsoft.Unity.Analyzers#186]
All Monobehaviours have the possibility of calling a Message by another object, and in this case, use a string. So, any method that inherits Monobehaiour with one or zero argument must not generate IDE0051.

        public class Test : MonoBehaviour
        {
                public string invokeString; // "InvokeMe" serialized
        
                private void Start()
                {
                    Invoke(invokeString, 0);
                    SendMessage(invokeString, transform); // can another Monobehaviour
                }
        
                private void InvokeMe()
                {
        
                }
         }

In this case, we should not suppress IDE0051

**Comment by heshuimu** [comment]
I think it would be better for OP to just mark the method as `[Preserved]` and create a suppressor around it so that the intention is clearer and does not involve reading Unity data. The problem with `SendMessage` is that the method name argument could be dynamically generated at runtime, which the analyzers have no way to correctly determine.

**Comment by sailro** [comment]
Yes I agree, let's do that. We will create another suppressor for handling `IDE0051` with implicit method usage when decorated with `PreservedAttribute`, `UsedImplicitly`, ...

So in your case @yonggyun-superlazy you'll just need to decorate your code like that:

```
            [UsedImplicitly]
            private void InvokeMe()
            {
    
            }
```
