### ISSUE TITLE
[Performance] Analyzer for SetPixels -> SetPixels32

### ISSUE THREAD

**Issue by sailro** [microsoft/Microsoft.Unity.Analyzers#55]
#### Problem statement
Context:

Unity is using two distinct representations for a RGBA Color:
[Color](https://docs.unity3d.com/ScriptReference/Color.html): Each color component is a **floating point value** with a range from 0 to 1. (this format is used inside all graphics cards and shaders). 
[Color32](https://docs.unity3d.com/ScriptReference/Color32.html): Each color component is a **byte value** with a range from 0 to 255. (32bit RGBA).

`Color32` is much faster and uses 4X less memory. `Color` and `Color32` can be implicitly converted to each other.

Note: sometimes though 32b RGBA is not enough (like for HDR or Dolby Vision or advanced color manipulation).

#### Proposed solution

Report a diagnostic for all SetPixels overloads (and propose to use SetPixels32 instead):
- UnityEngine.Texture2D
- UnityEngine.Texture3D
- UnityEngine.Cubemap
- UnityEngine.Texture2DArray
- UnityEngine.Texture3DArray
- UnityEngine.CubemapArray

Users targeting HDR/Dolby Vision scenarios can still disable this diagnostic.

**Comment by AlfishSoftware** [comment]
I really don't like this analyzer as is. The only thing it does is disable ***all*** usages of `SetPixels` indiscriminately, as if using it at all is deprecated or not recommended unless you say otherwise. Diagnostics are meant to catch ***probable*** mistakes. They should not force people to disable them on legitimate use cases with no workaround. And HDR is a very legitimate use case.

This is "guilty until proven innocent" logic, which is very wrong. We shouldn't just assume the programmer is making a dumb mistake by default, without any evidence for it.

It only makes sense to have it if it were doing some actual analysis, e.g. if could prove that it was used on a texture that was created with `linear` set to false, or inside a logical branch where `texture.isDataSRGB` was guaranteed true. Or if it's disabled by default. Or if there was ***always*** a better alternative, meaning this method should be treated as obsolete (but `SetPixelData` is not an alternative, it doesn't cover all of the same use cases).
