### ISSUE TITLE
Language features vs. .Net / Mono version?

### ISSUE THREAD

**Issue by aubergine10** [microsoft/Microsoft.Unity.Analyzers#78]
#### Problem statement

I'm new to C# dev and Unity dev. I have no idea which language features are supported by .Net 3.5
and Mono 2."0". I want to use latest language features, but don't want my code causing CTD.

Example from PR review where I added `<LangVersion>latest</LangVersion>` to a .csproj:

![image](https://user-images.githubusercontent.com/1386719/83271724-25e95f00-a1c2-11ea-9d01-287e7ae81686.png)

#### Proposed solution

A mapping between .Net version and language feature compatibility, warn/error whenever an incompatible feature is used for the given .Net version.

> Side note: How do I even get `Microsoft.Unity.Analyzers` in to VS2019 - doesn't seem to be a NuGet pkg?

**Comment by sailro** [comment]
For the side note:
https://github.com/microsoft/Microsoft.Unity.Analyzers/issues/80

Regarding LangVersion, it's a complex subject because as explained in your thread some features are directly handled by the compiler (and depending on the Unity version it is either an old mono compiler, a new mono compiler or even Roslyn), while other features need runtime support.

To illustrate this, Unity just announced support for C# 8 in 2020.2.a14 (minus default interface methods because the runtime support is not here yet).

For now this project is only about static code analysis, we don't even know about the Unity version used. So perhaps it is more something to be done in IDE extensions supporting Unity and/or Unity packages responsible for project generation.

**Comment by sailro** [comment]
Closing for now, we are currently discussing with Unity how to properly handle langVersion. This is something that will be probably handled by csproj/sln generators.
