### ISSUE TITLE
IDE0051 and IDE0060 on AssetPostprocessor static methods

### ISSUE THREAD

**Issue by aybe** [microsoft/Microsoft.Unity.Analyzers#85]
#### Problem statement

VS 16.6.2
VSTU 4.6.0.0

The following warnings are shown for the code sample below:

```
IDE0060	Remove unused parameter 'path'
IDE0051	Private member 'XXX' is unused
```

```
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using UnityEditor;

namespace Editor
{
    internal sealed class EnsureCSharp8Postprocessor : AssetPostprocessor
    {
        private static string OnGeneratedCSProject(string path, string content)
        {
            var document = XDocument.Parse(content);

            var root = document.Root;
            if (root is null)
                throw new ArgumentNullException(nameof(root));

            var ns = root.GetDefaultNamespace();

            var element = root.Descendants(ns + "LangVersion").SingleOrDefault();
            if (element == null)
                throw new ArgumentNullException(nameof(element));

            element.Value = "8.0";

            // ReSharper disable once ConvertToUsingDeclaration
            using (var writer = new Utf8StringWriter())
            {
                document.Save(writer);

                content = writer.ToString();
            }

            return content;
        }

        private sealed class Utf8StringWriter : StringWriter
        {
            public override Encoding Encoding => Encoding.UTF8;
        }
    }
}
```
#### Proposed solution

Both of these warnings should not be shown.

**Comment by sailro** [comment]
Yes we already suppress `IDE0060` and `IDE0051` for `MonoBehaviour` messages:
https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/doc/USP0005.md
https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/doc/USP0003.md

But indeed we have to do the same thing for other special types like `AssetPostProcessor`.

**Comment by ruslan-smirnov** [comment]
I'm not sure what I'm writing where I need to. But I have problem with Visual Studio 2019 with Unity Tools. I have code:

`

        private void Awake()
        {
        }

        private void Start()
        {
            GameSystems.Get<MessageSystem>().Subscribe<SceneLoadedGameMessage>(Handle_OnSceneLoaded);
            GameSystems.Get<SceneSystem>().Load(SceneID.Loader);
        }

`

IDE show potential fixes on Awake and Start - delete both methods) It's trouble is fixed already?

And Why it's happened? Because I opened right now VS 2017 and don't see trouble.

**Comment by sailro** [comment]
> I'm not sure what I'm writing where I need to. But I have problem with Visual Studio 2019 & Unity Tools. I have code:
> 
> `
> 
> ```
>     private void Awake()
>     {
>     }
> 
>     private void Start()
>     {
>         GameSystems.Get<MessageSystem>().Subscribe<SceneLoadedGameMessage>(Handle_OnSceneLoaded);
>         GameSystems.Get<SceneSystem>().Load(SceneID.Loader);
>     }
> ```
> 
> `
> 
> IDE show potential fixes IDE0051 on Awake and Start - delete both methods) It's trouble is fixed already?
> 
> And Why it's happened? Because I opened right now VS 2017 and don't see trouble.

Yes this is exactly what we handle with this project. So perhaps you are still using an old VS2019 version or our analyzers are not loaded (this is the case if VS2019 is not set as your preferred external Editor in Unity => Unity will only generate regular csproj files)

Compared to VS2017, VS2019 has added many diagnostics to help you maintain your codebase (that's why you don't see any with VS2017) and Microsoft.Unity.Analyzers provides VS with a better understanding of Unity projects by adding Unity specific diagnostics or by removing general C# diagnostics that don't apply to Unity projects.

**Comment by ruslan-smirnov** [comment]
Yeah, I removed all project files and recreated project via unity. Now it's working
