### ISSUE TITLE
CPU usage high

### ISSUE THREAD

**Issue by hs115488** [microsoft/Microsoft.Unity.Analyzers#91]
Is there anyway to lower the CPU Usage upon Visual Studio using Unity. I'd like to use VS rather than Rider

**Comment by sailro** [comment]
Hello,

Is your issue really related to our analyzers? If so could you elaborate a bit more so we can try to reproduce on our side? Analyzers are run in a low priority thread and should not impact drastically your IDE experience.

If the issue is more related to the VSTU extension, the best is to use `Help/Send Feeback/Report a problem` from Visual Studio. This will send all the interesting telemetry to help us diagnose the problem.

Thanks !
